bro_world_core:
    security:
        secured_path_regex: '^/api/(?!.*(security)|(test)|(doc)).*$'
    messenger:
        failed_retry:
            is_retryable: false
            waiting_time: 0
    media:
        api_base_url: '%env(API_MEDIA_BASE_URL)%'
    jwt_public_key: '%env(resolve:JWT_PUBLIC_KEY_PATH)%'
    elasticsearch:
        host: '%env(ELASTICSEARCH_HOST)%'
        username: '%env(ELASTICSEARCH_USERNAME)%'
        password: '%env(ELASTICSEARCH_PASSWORD)%'
